### ISSUE TITLE
Which Python versions are supported is a secret

### ISSUE THREAD

**Issue by ajdavis** [teepark/greenhouse#16]
You don't appear to list which Python versions you support. Who's allowed to know this information?

**Comment by ajdavis** [comment]
Ooh, sneaky. =)

**Comment by behackett** [comment]
For real? It would be helpful to know what versions of python greenhouse supports. I assume this answer means python 2.7 only?

**Comment by teepark** [comment]
Honestly I don't know. That was mostly a reaction to the language of the original issue.

There's no patching for the back-ported io module (2.6+), some version of python 3 worked at one point (modulo missing stdlib patching) but I haven't tested it in a while, and IIRC something happened in the stdlib around 2.7.8 or so that breaks the ssl patching.

I'm not keeping up with it all any more. There's no version I'd really call "supported".

**Comment by behackett** [comment]
Fair enough. 2.7.something it is then. Thanks. :-)

**Comment by behackett** [comment]
Oh, 2.7.8 started the backporting of a bunch of security stuff from 3.x. Though I think they only managed to get hashlib.pbkdf2_hmac done. 2.7.9 backports all the SSLContext stuff.

**Comment by teepark** [comment]
Yeah looks like it was 2.7.9. eventlet and gevent had the same issue - they changed the SSL module API.

http://bugs.python.org/issue22438

**Comment by behackett** [comment]
Heh, backporting major portions of python3's ssl module in a patch level security release. What could possibly go wrong? ;-)

**Comment by ajdavis** [comment]
Apologies for my tone at the beginning I was grouchy. Thanks for
responding.

**Comment by teepark** [comment]
@ajdavis no worries.

yeah this is exactly why I'm basically out of the game. greenhouse's differentiation from eventlet and gevent was supposed to be the completeness of the stdlib (and even some popular 3rd party libs) patching, but it's a huge job to keep up with everything and always support new things/versions in a way that doesn't break old things/versions.

I don't have the ability to maintain that kind of cross product, especially when I have no more day-job use of greenhouse.

**Comment by behackett** [comment]
No worries. We were just playing around with testing PyMongo and greenhouse and weren't sure what python versions were supported. No harm done. Thanks for the help!
